# Generated by Django 4.2.7 on 2026-02-28 19:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('pais_origen', models.CharField(blank=True, max_length=100)),
                ('biografia', models.TextField(blank=True)),
                ('foto', models.URLField(blank=True, help_text='URL de la foto del autor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'ordering': ['apellido', 'nombre'],
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100)),
                ('isbn', models.CharField(help_text='ISBN de 13 dígitos', max_length=13, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=100)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('paginas', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('idioma', models.CharField(default='Español', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_portada', models.URLField(blank=True)),
                ('stock', models.PositiveIntegerField(default=1, help_text='Cantidad de ejemplares disponibles', validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('mantenimiento', 'En Mantenimiento'), ('perdido', 'Perdido')], default='disponible', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio en Lempiras (L)', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valoracion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valoración de 0 a 5 estrellas', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libros', to='libros.autor')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros', to='libros.categoria')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Libros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('atrasado', 'Atrasado'), ('perdido', 'Perdido')], default='activo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['isbn'], name='libros_libr_isbn_88473c_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='libros_libr_titulo_8b1204_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='libros_libr_autor_i_ef6aa2_idx'),
        ),
    ]
